---
resource_types:
  - name: github-list-repos
    type: docker-image
    source:
      repository: quay.io/coralogix/concourse-resource-github-list-repos
      tag: v0.5.0
resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/dashaun-cloud/concourse-pipelines

jobs:
  - name: teams
    serial: true
    public: true
    plan:
      - get: repo
        trigger: true
        params: { depth: 1 }
      - task: process-team-configs
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
            - name: repo
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e
                
                apt-get update -q > /dev/null
                apt-get upgrade -y > /dev/null
                apt-get install curl -y > /dev/null
                
                curl https://concourse.dashaun.cloud/api/v1/cli?arch=amd64&platform=linux > /usr/local/bin/fly
                chmod +x /usr/local/bin/fly
                fly -h
                
                for team_file in repo/team-config/*.yml; do
                  team_name=$(basename "$team_file" .yml)
                  echo "Processing team: $team_name"
                  echo "Team file: $team_file"
                  fly -t local set-team --team-name=$team_name --config=$team_file --non-interactive
                done
