---
resources:
- name: every-3-hours
  type: time
  icon: clock-outline
  source:
    interval: 3h
- name: repo
  type: git
  icon: github
  source:
    uri: git@github.com:dashaun-demo/spring-petclinic.git
    private_key: |
      ((github-key))

    branch: main
    fetch_tags: true
    skip_ssl_verification: true

jobs:
- name: spring-application-advisor
  serial: true
  public: true
  plan:
  - get: every-3-hours
    trigger: true
  - get: repo
    trigger: true
  - task: spring-application-advisor
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          username: ((dockerhub-user))
          password: ((dockerhub-token))
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            set +x
            export GIT_TOKEN_FOR_PRS=((github-token))
            export ADVISOR_SERVER=http://100.101.0.61:8080
            source "/root/.sdkman/bin/sdkman-init.sh"
            cd repo
            sdk use java 21.0.2-graalce
            set -x
            advisor -version
            advisor build-config get
            advisor upgrade-plan get
            advisor upgrade-plan apply
            git status