---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dashaun-demo/spring-petclinic
    branch: main
    username: dashaun
    password: ((github-token))

jobs:
- name: spring-application-advisor
  serial: true
  public: true
  plan:
  - get: repo
    trigger: true
  - task: spring-application-advisor
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          username: ((dockerhub-user))
          password: ((dockerhub-token))
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            set +x
            export GIT_TOKEN_FOR_PRS=((github-token))
            export ADVISOR_SERVER=http://100.101.0.61:8080
            source "/root/.sdkman/bin/sdkman-init.sh"
            cd repo
            sdk install java 17.0.12-librca
            sdk install java 21.0.2-graalce
            sdk use java 21.0.2-graalce
            set -x
            advisor -version
            advisor build-config get
            cat target/.advisor/build-config.json | grep "dashaun-demo"
            advisor upgrade-plan get
            advisor upgrade-plan apply --debug --push