---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:dashaun-demo/spring-petclinic.git
    private_key: |
      ((github-key))
    branch: ((branch))
    skip_ssl_verification: true

jobs:
- name: unit-test
  serial: true
  public: true
  plan:
  - get: repo
    trigger: true
  - task: mvnw-clean-package
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          username: ((dockerhub-user))
          password: ((dockerhub-token))
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            set +x
            source "/root/.sdkman/bin/sdkman-init.sh"
            cd repo
            sdk use java 17.0.12-librca
            set -x
            ./mvnw -q clean package
  - task: spring-boot-build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            sleep 10
- name: integration-test
  serial: true
  public: true
  plan:
  - get: repo
    passed: [unit-test]
    trigger: true
  - task: integration-test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          username: ((dockerhub-user))
          password: ((dockerhub-token))
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            sleep 10
- name: smoke-test
  serial: true
  public: true
  plan:
    - get: repo
      passed: [integration-test]
      trigger: true
    - task: test-deploy
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            username: ((dockerhub-user))
            password: ((dockerhub-token))
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              sleep 10
- name: e2e-test
  serial: true
  public: true
  plan:
    - get: repo
      passed: [smoke-test]
      trigger: true
    - task: test-smoke
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            username: ((dockerhub-user))
            password: ((dockerhub-token))
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              sleep 10
- name: cleanup
  serial: true
  public: true
  plan:
    - get: repo
      passed: [e2e-test]
      trigger: true
    - task: test-smoke
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            username: ((dockerhub-user))
            password: ((dockerhub-token))
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              sleep 10