resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: feature-branches
    type: git-branches
    source:
      uri: https://github.com/dashaun-demo/spring-petclinic
      username: dashaun
      password: ((github-token))

  - name: concourse-pipelines
    type: git
    source:
      uri: https://github.com/dashaun-cloud/concourse-pipelines
      username: dashaun
      password: ((github-token))

jobs:
  - name: set-feature-pipelines
    plan:
      - in_parallel:
          - get: feature-branches
            trigger: true
          - get: concourse-pipelines
      - task: show-branches
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: dashaun/task-runner
              username: ((dockerhub-user))
              password: ((dockerhub-token))
              tag: latest
          inputs:
            - name: feature-branches
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cat feature-branches/branches.json
      - load_var: branches
        file: feature-branches/branches.json
      - across:
          - var: branch
            values: ((.:branches))
        set_pipeline: ((.:branch.name))
        file: concourse-pipelines/springone/branch.yml
        vars: {branch: ((.:branch.name)),
               github-token: ((github-token)),
               dockerhub-user: ((dockerhub-user)),
               dockerhub-token: ((dockerhub-token))}
