resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: branches
    type: git-branches
    icon: github
    source:
      uri: git@github.com:dashaun-demo/spring-petclinic.git
      private_key: |
        ((github-key))

  - name: pipelines
    type: git
    icon: github
    source:
      uri: git@github.com:dashaun-cloud/concourse-pipelines
      private_key: |
        ((github-key))

jobs:
  - name: set-feature-pipelines
    plan:
      - in_parallel:
          - get: branches
            trigger: true
          - get: pipelines
      - load_var: branches
        file: branches/branches.json
      - across:
          - var: branch
            values: ((.:branches))
        set_pipeline: ((.:branch.name))
        file: pipelines/springone/branch.yml
        vars: {branch: ((.:branch.name)),
               github-token: ((github-token)),
               dockerhub-user: ((dockerhub-user)),
               dockerhub-token: ((dockerhub-token)),
               github-key: ((github-key))}