---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dashaun-demo/spring-petclinic
    branch: main
    username: dashaun
    password: ((github-token))

jobs:
- name: unit-test
  serial: true
  public: true
  plan:
  - get: repo
    trigger: true
  - task: mvnw-clean-package
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            source "/root/.sdkman/bin/sdkman-init.sh"
            whoami
            env
            pwd
            export TC_CLOUD_TOKEN=((tcc-token))
            cd repo
            sdk install java 17.0.12-librca
            sdk use java 17.0.12-librca
            ./mvnw -q clean package
- name: integration-test
  serial: true
  public: true
  plan:
  - get: repo
    passed: [unit-test]
    trigger: true
  - task: integration-test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dashaun/task-runner
          tag: latest
      inputs:
        - name: repo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            whoami
- name: test-deploy
  serial: true
  public: true
  plan:
    - get: repo
      passed: [integration-test]
      trigger: true
    - task: test-deploy
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami
- name: test-smoke
  serial: true
  public: true
  plan:
    - get: repo
      passed: [test-deploy]
      trigger: true
    - task: test-smoke
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami
- name: test-rollback-deploy
  serial: true
  public: true
  plan:
    - get: repo
      passed: [test-smoke]
      trigger: true
    - task: test-smoke
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami
- name: test-rollback-smoke
  serial: true
  public: true
  plan:
    - get: repo
      passed: [test-rollback-deploy]
      trigger: true
    - task: test-smoke
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami
- name: stage-deploy
  serial: true
  public: true
  plan:
    - get: repo
      passed: [test-rollback-smoke]
      trigger: true
    - task: stage-deploy
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami
- name: stage-e2e
  serial: true
  public: true
  plan:
    - get: repo
      passed: [stage-deploy]
      trigger: true
    - task: stage-e2e
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dashaun/task-runner
            tag: latest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              whoami